### PR TITLE
Keymapping fix

### LINKED ISSUE #457: Adding a listener in a listener
Seems to be a bad idea, I miss this one during review.
https://github.com/STORM-IRIT/Radium-Engine/blob/e39e9a7440ae1f7bebcb8adea9b55e7bc23fa19d/src/GuiBase/Viewer/Viewer.cpp#L66

I'll prepare an update, but I have differents solutions in mind :
directly call camera and gizmo register method,
add an helper, that register the three callbacks,
move the callback registration in base app ... but it means any base app has to have a gizmo and a camera.

### PR DESCRIPTION
**Pull request by dlyr**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
bug fix #457

* **What is the current behavior?** (You can also link to an open issue here)
the Viewer::registerKeymapping, which should act as a call back called by keyMappingManager, add also callback's for camera and gizmo to the keyMappingManager
the PR also cleanup file management in keyMappingManager, I was not sure of the expected behavior, so I correct them to what I expect to be correct, but comment are welcoms.

* **What is the new behavior (if this is a feature change)?**
an helper function of the viewer is added to register all callback's to keyMappingManager.
I don't chech minimalapp, which register camera and viewer only, it's maybe a mistake ... or not.

### CODE REVIEW

File: src/GuiBase/Viewer/Viewer.cpp [hunk 1]
```diff
@@ -61,11 +61,17 @@ KeyMappingViewer;
...
+void Gui::Viewer::setupKeyMappingCallbacks() {
     auto keyMappingManager = Gui::KeyMappingManager::getInstance();
+
     keyMappingManager->addListener( Gui::TrackballCamera::registerKeyMapping );
     keyMappingManager->addListener( Gui::GizmoManager::registerKeyMapping );
-    m_keyMappingContext = keyMappingManager->getContext( "ViewerContext" );
+    keyMappingManager->addListener( registerKeyMapping );
+}
+
+void Gui::Viewer::registerKeyMapping() {
```
Comment (nmellado) [inline src/GuiBase/Viewer/Viewer.cpp]:
```suggestion
void Gui::Viewer::configureKeyMapping() {
```
