### PR TITLE
Fix issue 510;

### LINKED ISSUE #510: TriangleMeshComponent's RenderObject's Index
I tried to use the SkeletonBasedAnimation plugin with the current master branch and I went across an issue with the `TriangleMeshComponent` about accessing the RO Index.
Actually, it is stored as `TriangleMeshComponent::m_meshIndex` but is given access through the `ComponentMessenger` via `GeometryComponent::setupIO` which uses `GeometryComponent::getRenderObjectIndex` which returns `GeometryComponent::m_roIndex`.
But this one is not set.
PR coming

### PR DESCRIPTION
**Pull request by hoshiryu**
UPDATE the form below to describe your PR.

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fix #510 

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

File: src/Engine/Component/GeometryComponent.cpp [hunk 1]
```diff
@@ -54,15 +54,17 @@ const Index* GeometryComponent::roIndexRead() const {
 TriangleMeshComponent::TriangleMeshComponent( const std::string& name,
                                               Entity* entity,
                                               const Ra::Core::Asset::GeometryData* data ) :
-    GeometryComponent( name, entity ), m_displayMesh( nullptr ) {
+    GeometryComponent( name, entity ),
+    m_displayMesh( nullptr ) {
```
Comment (MathiasPaulin) [inline src/Engine/Component/GeometryComponent.cpp]: Not formatted according to the required clang-format. Use clang-format >= 9.0

Comment (hoshiryu) [reply src/Engine/Component/GeometryComponent.cpp]: I cannot install clang-format version 9 on my laptop, so please do so and PR on my branch
