### PR TITLE
Fix entity manager

### LINKED ISSUE #307: Bad Entity naming
When creating an entity through an existing name, this name is checked only once for existence and a "_" is appended to it.
Hence, the new name is not checked for existence again, which leads to entities with the same name if there are more than two of them.

### PR DESCRIPTION
**Pull request by hoshiryu**
* **Please check if the PR fulfills these requirements**
- [ ] Is the Pull-Request done against the right branch:
  - `master`: for hotfixes not impacting the API
  - `master-v1`: for changes related to the Radium Stable Release V1.
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

Fixes #307
Fixes entity management to deal with removal (see #308)

### CODE REVIEW

File: src/Engine/Managers/EntityManager/EntityManager.cpp [hunk 1]
```diff
@@ -90,13 +94,11 @@ namespace Ra
...
-            uint size = m_entities.size();
-
-            entities.reserve( size );
+            entities.reserve( m_entities.size() );
 
-            for ( uint i = 0; i < size; ++i )
+            for ( const auto& e : m_entities )
             {
-                entities.push_back( m_entities[i].get() );
+                entities.push_back( e.get() );
```
Comment (nmellado) [inline src/Engine/Managers/EntityManager/EntityManager.cpp]: Considering using `std::copy` (see https://github.com/STORM-IRIT/Radium-Engine/pull/309#pullrequestreview-120221716)
