### PR TITLE
[tests] fix #855 epsilon so that io test work with double

### LINKED ISSUE #855: Test IO/VolumesLoader fails when compiled with Scalar=double
Error logs: https://github.com/STORM-IRIT/Radium-Engine/actions/runs/1709898742

The problems seems to come from the fact that volume files are stored in `float`: numbers are loaded from files, casted to `double`, and then compared to `double` constants with an epsilon value in `double`. This test is very likely to fail and would require a `float` epsilon value.

### PR DESCRIPTION
**Pull request by dlyr**
Increase epsilon booster so that io tests work with Scalar=double, while the reader and stored data are floats.

### CODE REVIEW

File: tests/unittest/IO/volumeloader.cpp [hunk 1]
```diff
@@ -93,7 +95,9 @@ TEST_CASE( "IO/VolumesLoader", "[IO]" ) {
         auto binsize = volumeData->binSize();
         REQUIRE( ( Math::areApproxEqual( binsize[0], 1._ra ) &&
                    Math::areApproxEqual( binsize[1], 1._ra ) &&
-                   Math::areApproxEqual( binsize[2], 1.4_ra ) ) );
+                   // if Scalar = double, since reader use float, increase epsilon by float/double
+                   // epsilon ratio
+                   Math::areApproxEqual( binsize[2], 1.4_ra, 436870912_ra ) ) );
```
Comment (nmellado) [inline tests/unittest/IO/volumeloader.cpp:100]: Couldn't we have something like this (with the proper syntax):
```
Math::areApproxEqual( binsize[2], 1.4_ra, epsilon<float>()/epsilon<double>() ) ) );
```

Comment (dlyr) [reply tests/unittest/IO/volumeloader.cpp:100]: yes we can

File: tests/unittest/IO/volumeloader.cpp [hunk 2]
```diff
@@ -93,7 +93,12 @@ TEST_CASE( "IO/VolumesLoader", "[IO]" ) {
         auto binsize = volumeData->binSize();
         REQUIRE( ( Math::areApproxEqual( binsize[0], 1._ra ) &&
                    Math::areApproxEqual( binsize[1], 1._ra ) &&
-                   Math::areApproxEqual( binsize[2], 1.4_ra ) ) );
+                   // if Scalar = double, since reader use float, increase epsilon by float/double
+                   // epsilon ratio (test hack ;))
+                   Math::areApproxEqual( binsize[2],
+                                         1.4_ra,
+                                         Scalar { std::numeric_limits<float>::epsilon() /
+                                                  std::numeric_limits<double>::epsilon() } ) ) );
```
Comment (nmellado) [inline tests/unittest/IO/volumeloader.cpp:101]:
```suggestion
                                                  std::numeric_limits<Scalar>::epsilon() } ) ) );
```

Comment (dlyr) [reply tests/unittest/IO/volumeloader.cpp]: This works for both float and double on my computer.

**Review by nmellado — APPROVED** [review]
