### PR TITLE
Students l3 2021

### LINKED ISSUE #736: Master branch not compiling
When compiling Radium's master branch from scratch I get the following error:
```
18:40:39: Running steps for project radiumproject...
18:40:39: Starting: "/usr/bin/cmake" --build . --target all -- && make install
[  0%] Built target ExternalCore
[  0%] Built target versionFileTouchForRebuild
Scanning dependencies of target Core
[  0%] Building CXX object src/Core/CMakeFiles/Core.dir/Version.cpp.o
[  1%] Linking CXX shared library libCore.so
[ 23%] Built target Core
[ 23%] Built target ExternalIO
[ 24%] Linking CXX shared library libIO.so
[ 29%] Built target IO
[ 29%] Built target RadiumEngineShaders
[ 29%] Building CXX object src/Engine/CMakeFiles/Engine.dir/Data/BlinnPhongMaterial.cpp.o
In file included from /usr/include/c++/8/memory:80,
                 from /usr/include/c++/8/thread:39,
                 from /home/hoshiryu/dev/Radium_update/Radium-Engine/src/Core/CoreMacros.hpp:123,
                 from /home/hoshiryu/dev/Radium_update/Radium-Engine/src/Engine/RaEngine.hpp:2,
                 from /home/hoshiryu/dev/Radium_update/Radium-Engine/src/Engine/Data/BlinnPhongMaterial.hpp:3,
                 from /home/hoshiryu/dev/Radium_update/Radium-Engine/src/Engine/Data/BlinnPhongMaterial.cpp:1:
/usr/include/c++/8/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = globjects::State]’:
/usr/include/c++/8/bits/unique_ptr.h:274:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = globjects::State; _Dp = std::default_delete<globjects::State>]’
/home/hoshiryu/dev/Radium_update/Radium-Engine/src/Engine/RadiumEngine.hpp:396:61:   required from here
/usr/include/c++/8/bits/unique_ptr.h:79:16: error: invalid application of ‘sizeof’ to incomplete type ‘globjects::State’
  static_assert(sizeof(_Tp)>0,
                ^~~~~~~~~~~
make[2]: *** [src/Engine/CMakeFiles/Engine.dir/build.make:63: src/Engine/CMakeFiles/Engine.dir/Data/BlinnPhongMaterial.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1499: src/Engine/CMakeFiles/Engine.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
18:40:44: The process "/usr/bin/cmake" exited with code 2.
Error while building/deploying project radiumproject (kit: Desktop)
When executing step "CMake Build"
18:40:44: Elapsed time: 00:04.
```

Is there something wrong with my compiler? I use GCC 8.3

### PR DESCRIPTION
**Pull request by MathiasPaulin**
closes #736

This PR allows to configure and build Radium with cmake version 3.13 and over corresponding to what is requested in all the CMakeLists.txt files (e.g., in the main CMakeLists.txt : `cmake_minimum_required(VERSION 3.13)`
The only effect resulting from configuring with cmake 3.13 instead of 3.15 is some misaligned messages.

This PR also allows to compile with gcc-8 as requested in the file `cmake/compilerVersion.cmake` 
No effect is observed for this

CAUTION : do not delete the branch after merge

### CODE REVIEW

**Comment by dlyr** [comment]
**CHECK FORMAT FAIL**
You can trigger automatic format action on github with the special branch `gh-formatter`.
This special branch trigger clang-format and add a commit with the modified files.

```bash
git branch -D gh-formatter
git switch -c gh-formatter
```

Ensure you have the .github/workflows/formatter.yml file, if not add it to your branch from
[here](https://github.com/STORM-IRIT/Radium-Engine/tree/master/.github/workflows).


**ADAPT REMOTE TO YOUR SETUP**, here origin is supposed to correspond to your repo: `STORM-IRIT/Radium-Engine`
```bash
git push -f --set-upstream origin gh-formatter
```
Wait for git action to finish, it will add a commit to orogin/gh-formatter.
Then take this commit back to your branch and update your PR:
```
git pull
git checkout students-l3-2021
git reset --hard gh-formatter
git push
```

File: src/Gui/Timeline/TimelineScrollArea.cpp [hunk 1]
```diff
@@ -154,7 +154,7 @@ void TimelineScrollArea::wheelEvent( QWheelEvent* event ) {
         }
 
         double hScroll = horizontalScrollBar()->value();
-        double x       = event->position().x();
+        double x       = event->x();
```
Comment (dlyr) [inline src/Gui/Timeline/TimelineScrollArea.cpp:157]: QWheelEvent::x() is deprecated since 5.15. Consider adding this 

```suggestion
#if QT_VERSION < QT_VERSION_CHECK( 5, 15, 0 )
            double x = event->x();
#else
            double x =event->position().x();
#endif
```

If fine with this, I could add similar code in all wheel events to remove deprecated warnings.

**Review by dlyr — CHANGES_REQUESTED** [review]

File: cmake/cleanCppExtensions.cmake [hunk 2]
```diff
@@ -168,8 +168,11 @@ macro(addMiscTargets)
     #     -p=./
     #     COMMAND echo ""
     #     )
-    list(POP_BACK CMAKE_MESSAGE_INDENT)
-
+    if(${CMAKE_VERSION} VERSION_LESS "3.15.0")
```
[the remark this answers is not in the document]
Comment (MathiasPaulin) [reply cmake/cleanCppExtensions.cmake:171]: Well, hard to do as there is no common cmake include for all these files. 
But I can replace this by a "naive" implementation of `list(pop_back `by using `list(remove_at`
Doing this, messages will stay correctly formatted whatever the cmake version used for configure.
So, I propose to replace all these tests by : 
```cmake
list(REMOVE_AT CMAKE_MESSAGE_INDENT -1)
```
see doc at https://cmake.org/cmake/help/v3.13/command/list.html#remove-at

[the remark this answers is not in the document]
Comment (dlyr) [reply cmake/cleanCppExtensions.cmake:171]: this solution seems fine.

File: src/Gui/Timeline/TimelineScrollArea.cpp (hunk 1 above)
Comment (MathiasPaulin) [reply src/Gui/Timeline/TimelineScrollArea.cpp:157]: I'm fine with this, even if I didn't find this deprecation in the documentation https://doc.qt.io/qt-5/qmouseevent.html
Qt 5.15 is the last qt5 version if i understand well the Qt documentation and Radium is not Qt6 compatible (but this might be done in the future ?)

Comment (dlyr) [reply src/Gui/Timeline/TimelineScrollArea.cpp]: Well, it's because it's a Wheel event, not a Mouse event
Qt doc https://doc.qt.io/qt-5/qwheelevent.html do not mention .x() at all since it's deprecated ( see https://github.com/qt/qtbase/blob/40143c189b7c1bf3c2058b77d00ea5c4e3be8b28/src/gui/kernel/qevent.h#L216 )

Comment (MathiasPaulin) [reply src/Gui/Timeline/TimelineScrollArea.cpp]: OK, BTW, I've pushed the suggested change.

**Review by nmellado — DISMISSED** [review]

**Review by dlyr — APPROVED** [review]
I have cleaned up the history, and change one include (when searching for possible qt deprecation ...)

**Review by nmellado — APPROVED** [review]
