### PR TITLE
Camera frame issues solved

### LINKED ISSUE #810: Camera issues
There are several issues with camera frame : 
  - Assimp loader generate wrong camera frames compared to references
  - The camera frame, when used for rendering, does not take into account the transformation of the entity where the camera is attached. This is not coherent with the way frames are computed for geometric object. If both a mesh and a camera is attached to an animated entity, only the mesh and the camera representation (a mesh) follow the animation. The camera frame does not.
 
Due to these, it is very hard to animate a camera from an animation of its entity or to have the same view of a scene when loading scenes with assimp loader.

### PR DESCRIPTION
**Pull request by MathiasPaulin**
Closes #810 and #808

_Check if you branch history is PR compatible_
- Your branch need to be up to date with origin/master AND to have linear history (i.e. no merge commit).
- Update your git repository `git fetch origin` if origin is this remote
- Check with the script provided in `scripts/is-history-pr-compatible.sh`
- You must use clang-format style
_These checks are enforced by github workflow actions_
_Please refer to the corresponding log in case of failure_

_UPDATE the form below to describe your PR._

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix

* **What is the current behavior?** (You can also link to an open issue here)

See issue #810 : camera frame are wrong when loaded by assimp loader and camera frame does not follow the entity transformation

* **What is the new behavior (if this is a feature change)?**

Camera frame are correct when loaded using assimp loader
The active camera frame, managed the CameraManager takes into account the entity transformation : 
 - when requesting a camera from the camera manager, the frame of the camera is computed to take into account the transformation of the entity
 - if an entity is animated, the frame of the active camera is automatically updated so that the active camera is also animated.
 - The viewer now observe the Camera manager so that when the active camera is modified (either by switching the camera or due to the entity animation), it could update its CameraManipulator internal state.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No.

* **Other information**:

This PR also add a demonstration on how to animate an entity. In this demonstration, a system animate an entity and any component attached to this entity (geometry, Camera)  is then animated also.
The demo show the benefit of this PR as only the entity must be animated. 
 - Geometry components follow the transformation of the entity (this was already the case in the previous Radium version)
 - Camera component follow the animation also and when the camera is active, the viewer render the scene from the animated camera (this was not the case before this PR)
 -

### CODE REVIEW

File: src/Engine/Scene/Entity.hpp [hunk 1]
```diff
@@ -77,6 +81,8 @@ class RA_ENGINE_API Entity : public Core::Utils::IndexedObject
     bool m_isAabbValid {false};
     Core::Aabb m_aabb;
 
+    /// Listeners on Entity Transformation changes
+    Core::Utils::Observable<const Entity*> m_transformationObservers;
```
Comment (nmellado) [inline src/Engine/Scene/Entity.hpp:85]: Another option would be to mark `m_transformationObservers` as `mutable`, so the method `transformationObservers` could be kept as `const`. This would simplify user code, don't you think ?

File: tests/ExampleApps/EntityAnimationDemo/main.cpp [hunk 2]
```diff
@@ -0,0 +1,231 @@
...
+    explicit DemoWindow( uint w = 800, uint h = 640, QWidget* parent = nullptr ) :
+        Ra::Gui::SimpleWindow::SimpleWindow( w, h, parent ) {}
+
+    //! [Configure Custom KeyEvent for the window]
+    void configure() override {
+        // <alt>+F will switch to default camera
+        // <alt>+C will toggle on cameras
+        // these customs events are only here for demonstration purposse.
+        // events expressed for an apple french keyboard
+        getViewer()->addKeyPressEventAction(
```
Comment (nmellado) [inline tests/ExampleApps/EntityAnimationDemo/main.cpp:55]: These events look nice. Shall we add them to `SimpleWindows` as default ?

File: src/Engine/Scene/Entity.hpp (hunk 1 above)
Comment (MathiasPaulin) [reply src/Engine/Scene/Entity.hpp:85]: I though about that, yes. It could be simpler. I'll test it.

File: tests/ExampleApps/EntityAnimationDemo/main.cpp (hunk 2 above)
Comment (MathiasPaulin) [reply tests/ExampleApps/EntityAnimationDemo/main.cpp:55]: The viewer, and so the `SimpleWindow`, already has an event to switch cameras in turn : `<ALT>+c` Key event. 
So, there is no need for these that are redundant with viewer switching.
If an application want a direct access to the camera, it is easy to add custom event, even on SimpleWindow, without defining a Custom Window as in this demo ... I'll simplify more the demo to do that.

File: tests/ExampleApps/EntityAnimationDemo/main.cpp [hunk 3]
```diff
@@ -0,0 +1,184 @@
...
+        //! [Creating the cube]
+        auto cube = Geometry::makeSharpBox( {0.5f, 0.5f, 0.5f}, Utils::Color::Green() );
+        //! [Creating the Cube]
+
+        //! [Create a geometry component with the cube]
+        auto c = new Scene::TriangleMeshComponent(
+            "Fixed cube geometry", e, std::move( cube ), nullptr );
+        //! [Create a geometry component with the cube]
+    }
+    //! [Create the demo fixed component]
```
Comment (nmellado) [inline tests/ExampleApps/EntityAnimationDemo/main.cpp:115]:
```suggestion
```

File: tests/ExampleApps/EntityAnimationDemo/main.cpp [hunk 4]
```diff
@@ -0,0 +1,184 @@
...
+
+    //! [Cache the camera manager]
+    auto cameraManager = static_cast<Scene::DefaultCameraManager*>(
+        app.m_engine->getSystem( "DefaultCameraManager" ) );
+    //! [Cache the camera manager]
+
+    //! [Add usefull custom key events]
+    app.m_mainWindow->getViewer()->addKeyPressEventAction(
+        "switchCam0", "Key_0", "ShiftModifier", "", "false", [cameraManager]( QKeyEvent* event ) {
+            cameraManager->activate( event->key() - '0' );
```
Comment (nmellado) [inline tests/ExampleApps/EntityAnimationDemo/main.cpp]:
```suggestion
            // Convert ascii code to camera index: https://stackoverflow.com/a/30727561
            cameraManager->activate( event->key() - '0' );
```

File: tests/ExampleApps/EntityAnimationDemo/main.cpp (hunk 3 above)
Comment (MathiasPaulin) [reply tests/ExampleApps/EntityAnimationDemo/main.cpp]: this is the end of a nested snippet ...

**Review by nmellado — APPROVED** [review]

**Comment by nmellado** [comment]
Ready to merge when up to date with `release_candidate`.
