### PR TITLE
Fix skinning

### LINKED ISSUE #343: Broken skinning
On branch master-v1, the skinning plugin is broken: neither LBS or DQS work correctly.

### PR DESCRIPTION
**Pull request by hoshiryu**
* **Please check if the PR fulfills these requirements**
- [x] Is the Pull-Request done against the right branch:
  - `master-v1`: for changes related to the Radium Stable Release V1.
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR fixes #343 , which was due to non deep copy of attributes in `TriangleMesh`.
Also fixes compilation error with AppleClang due to the c++17 standard modification regarding std::random_shuffle.

* **What is the current behavior?** (You can also link to an open issue here)
No deep copy of attributes when copying a `TriangleMesh`.

* **What is the new behavior (if this is a feature change)?**
No copy of attributes when copying a TriangleMesh.
Copy of needed/all attributes from the corresponding methods, plus improved management of attributes addition/deletion in AttribManager.
Thus, there is no shallow copies anymore.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
The `TriangleMesh` doesn't give access to its `AttribManager` anymore, it only exposes a reduced interface for it.

* **Other information**:

### CODE REVIEW

File: src/Core/Utils/Attribs.hpp [hunk 1]
```diff
@@ -138,19 +139,36 @@ class AttribManager
 {
   public:
     using value_type = AttribBase*;
-    using Container = std::vector<value_type>;
+    using Container = Ra::Core::IndexMap<value_type>;
```
Comment (dlyr) [inline src/Core/Utils/Attribs.hpp]: Are we sure to switch from vector to deque as container structure ?

Comment (hoshiryu) [reply src/Core/Utils/Attribs.hpp]: When adding the tests for deep copy, i run into issues regarding deleted attributes.
The thing with the vector, we have to manage attributes deletion in a correct way, which was not the case: the test application crashed (segfault) because some `Attrib *` were null, and thus I had to check for it in a loop like
```
for ( auto attr : manager.attribs() )
```
which I think shouldn't be mandatory.

Using an `IndexMap` provides a nice and simple way to deal with attribute suppresion.
However, regarding `Handle` invalidation, the map will segfault when trying to access a deleted attribute from an old `Handle` to it.
This might be avoided by returning a `nullptr` if a `Handle` points to an invalid map entry.
Also to be noted that if the entry pointed by the old `Handle` has been replaced, this might be a problem too.

File: src/Core/Mesh/TriangleMesh.hpp [hunk 2]
```diff
@@ -19,67 +17,83 @@ namespace Core
...
         return m_vertexAttribs.getAttrib( m_verticesHandle ).data();
     }
-    NormalAttribHandle::Container& normals()
-    {
-        return m_vertexAttribs.getAttrib( m_normalsHandle ).data();
+    const PointAttribHandle::Container& vertices() const {
+        return m_vertexAttribs.getAttrib( m_verticesHandle ).data();
     }
 
-    const PointAttribHandle::Container& vertices() const
```
Comment (nmellado) [inline src/Core/Mesh/TriangleMesh.hpp]: Why removing the `vertices () const` method ?

File: src/Core/Mesh/TriangleMesh.hpp [hunk 3]
```diff
@@ -19,67 +17,83 @@ namespace Core
...
+    using Vec4AttribHandle = AttribHandle<Vector4>;
+    using Face = VectorNui;
 
     /// Create an empty mesh.
     inline TriangleMesh() { initDefaultAttribs(); }
-    /// Copy constructor and assignment operator
-    /// \warning No deep copy of attributes !
+
+    /// Copy constructor and assignment operator.
+    /// Note: shallow copy of attributes.
```
Comment (nmellado) [inline src/Core/Mesh/TriangleMesh.hpp]: From my point of view, keeping the shallow copy by default is misleading. Do you have a specific need for that ?

I see that could be useful to perform partial copies, in that case we need to have a mechanism for that.

File: src/Core/Mesh/TriangleMesh.hpp (hunk 2 above)
Comment (hoshiryu) [reply src/Core/Mesh/TriangleMesh.hpp]: actually it hasn't been removed, the style added the `{` at the end of the line

File: src/Core/Mesh/TriangleMesh.hpp (hunk 3 above)
Comment (hoshiryu) [reply src/Core/Mesh/TriangleMesh.hpp]: Well, I had a discussion with @dlyr about that point.
When doing a deep copy of a mesh, you may need only some attributes you need / are aware of, not all. I don't really remember all the discussion though, but I ended up restoring shallow copy as the default behavior.

Comment (nmellado) [reply src/Core/Mesh/TriangleMesh.hpp]: So we wait @dlyr is back before taking a decision.

File: src/Core/Mesh/TriangleMesh.hpp (hunk 2 above)
Comment (nmellado) [reply src/Core/Mesh/TriangleMesh.hpp]: ok, my bad, the diff visualization was misleading

File: src/Core/Mesh/TriangleMesh.hpp (hunk 3 above)
Comment (hoshiryu) [reply src/Core/Mesh/TriangleMesh.hpp]: Actually, the shallow copy is highly appreciated as the default behavior for functions/methods returning a `TriangleMesh`.
Thus I left it as is, renamed `copyAttribs` into `partialCopy` and added a `fullCopy` method.

File: src/Core/Utils/Attribs.hpp (hunk 1 above)
Comment (hoshiryu) [reply src/Core/Utils/Attribs.hpp]: Random access to a deque element is constant time (https://en.cppreference.com/w/cpp/container/deque)

File: src/Core/Utils/Attribs.hpp [hunk 4]
```diff
@@ -206,21 +224,21 @@ class AttribManager
         Attrib<T>* attrib = new Attrib<T>;
         attrib->setName( name );
 
-        auto itr = std::find_if( m_attribs.begin(), m_attribs.end(),
-                                 []( AttribBase* b ) { return b == nullptr; } );
-        if ( itr != m_attribs.end() )
-        {
+        auto it = std::find_if( m_attribs.begin(), m_attribs.end(),
+                                [&name](const auto& a){ return a->getName() == name; } );
```
[the remark this answers is not in the document]
Comment (hoshiryu) [reply src/Core/Utils/Attribs.hpp]: No since the Attributes are now stored in an IndexMap

File: src/Core/Mesh/TriangleMesh.hpp [hunk 5]
```diff
@@ -19,67 +17,89 @@ namespace Core
...
+    /// For deep copy of attributes, use the partialCopy or fullCopy methods.
+    /// Note: Directly using the AttribManager is highly discouraged.
     TriangleMesh( const TriangleMesh& ) = default;
     TriangleMesh& operator=( const TriangleMesh& ) = default;
 
+    /// Copy only the required attributes (deep copy).
+    /// The position and normal attributes are always copied, no need to provide their handles.
+    /// Note: The original handles are not valid for the mesh copy.
+    template <typename... Handles>
+    void partialCopy( const TriangleMesh& input, Handles... attribs );
```
Comment (nmellado) [inline src/Core/Mesh/TriangleMesh.hpp]: The name of the method is to me very confusing.
I would prefer something like `copyAttributes`, which express a bit more what's happening when the method is called.
Also, I don't see why the positions and normals are necessary copied. I could understand this for the positions, but in some cases you might have meshes without normals.

File: src/Core/Mesh/TriangleMesh.hpp [hunk 6]
```diff
@@ -19,67 +17,89 @@ namespace Core
...
+
+    /// Copy all the attributes (deep copy).
+    /// Note: The original handles are also valid for the mesh copy.
+    inline void fullCopy( const TriangleMesh& input );
```
Comment (nmellado) [inline src/Core/Mesh/TriangleMesh.hpp]: Same as above, I've found the name confusing. `copy` is enough I believe.

File: src/Core/Mesh/TriangleMesh.hpp [hunk 7]
```diff
@@ -19,67 +17,89 @@ namespace Core
...
+    /// The handle for normals, making request faster.
     NormalAttribHandle m_normalsHandle;
 
-    inline void initDefaultAttribs()
-    {
+    /// Sets the default attribs.
+    inline void initDefaultAttribs() {
         m_verticesHandle =
             m_vertexAttribs.addAttrib<PointAttribHandle::value_type>( "in_position" );
         m_normalsHandle = m_vertexAttribs.addAttrib<NormalAttribHandle::value_type>( "in_normal" );
```
Comment (nmellado) [inline src/Core/Mesh/TriangleMesh.hpp]: Do we always have normals ?

File: src/Core/Utils/Attribs.hpp (hunk 1 above)
Comment (nmellado) [reply src/Core/Utils/Attribs.hpp]: >This might be avoided by returning a `nullptr` if a `Handle` points to an invalid map entry.

I'm ok with this. If @dlyr agrees too, it can be added to the code.

> Also to be noted that if the entry pointed by the old Handle has been replaced, this might be a problem too.

This needs to be mentioned in the user documentation

File: src/Core/Utils/Attribs.hpp [hunk 8]
```diff
@@ -134,23 +127,70 @@ class AttribHandle
...
+    AttribManager& operator=( const AttribManager& m ) = default;
+
+    // Deep copy of attributes
+    /// Base copy, does nothing.
+    void partialCopy( const AttribManager& m ) {}
+
+    /// Deep copy of some attributes.
+    /// Note: if some attrib already exist, it will be replaced but not de-allocated.
+    template <class T, class... Handle>
+    void partialCopy( const AttribManager& m, const AttribHandle<T>& attr, Handle... attribs ) {
```
Comment (nmellado) [inline src/Core/Utils/Attribs.hpp]: Change names as requested for `TriangleMesh`

File: src/Core/Utils/Attribs.hpp [hunk 9]
```diff
@@ -134,23 +127,70 @@ class AttribHandle
...
+        auto h = addAttrib<T>( a.getName() );
+        getAttrib( h ).data() = a.data();
+        // deal with other attribs
+        partialCopy( m, attribs... );
+    }
 
-    /// const acces to attrib vector
-    const Container& attribs() const { return m_attribs; }
+    /// Deep copy of all attributes.
+    void fullCopy( const AttribManager& m ) {
```
Comment (nmellado) [inline src/Core/Utils/Attribs.hpp]: Change names as requested for `TriangleMesh`

File: src/Core/Utils/Attribs.hpp [hunk 10]
```diff
@@ -186,78 +225,73 @@ class AttribManager
...
-    {
-        return *static_cast<Attrib<T>*>( m_attribs[h.m_idx] );
+    inline const Attrib<T>& getAttrib( AttribHandle<T> h ) const {
+        return *static_cast<Attrib<T>*>( m_attribs.at( h.m_idx ) );
     }
 
-    /// Add attribute by name
+    /// Add attribute by name.
+    /// Note: If an attribute with the same name already exists,
+    ///  it will be replaced but not de-allocated.
```
Comment (nmellado) [inline src/Core/Utils/Attribs.hpp]: Add doxygen `\warning` command instead of `Note:`

File: src/Core/Mesh/TriangleMesh.hpp (hunk 7 above)
Comment (dlyr) [reply src/Core/Mesh/TriangleMesh.hpp]: yes
if not, there are set to 0 ?
but normals are initialized everywhere as a always present attrib

File: src/Core/Utils/Attribs.hpp (hunk 1 above)
Comment (dlyr) [reply src/Core/Utils/Attribs.hpp]: well, the index map access, with at(index), perform a find on the deque ... I'm not convienced here we can afford the performance penality

File: Docs/mesh.md [hunk 11]
```diff
@@ -40,15 +44,18 @@ For instance
...
-        auto handle1 = m.attribManager().addAttrib<Vector3>( "vector3_attrib" );
-        m.attribManager().getAttrib( handle1 ).data().reserve( 3 );
-        m.attribManager().getAttrib( handle1 ).data().push_back( {1, 1, 1} );
-        m.attribManager().getAttrib( handle1 ).data().push_back( {2, 2, 2} );
-        m.attribManager().getAttrib( handle1 ).data().push_back( {3, 3, 3} );
+        auto handle1 = m.addAttrib<Vector3>( "vector3_attrib" );
+        m.getAttrib( handle1 ).data().reserve( 3 );
+        m.getAttrib( handle1 ).data().push_back( {1, 1, 1} );
+        m.getAttrib( handle1 ).data().push_back( {2, 2, 2} );
+        m.getAttrib( handle1 ).data().push_back( {3, 3, 3} );
```
Comment (nmellado) [inline Docs/mesh.md]: Can I do this: 
```
auto handle1 = m.addAttrib<Vector3>( "vector3_attrib" );
auto &buf = m.getAttrib( handle1 ).data();
buf.reserve( 3 );
buf.push_back( {1, 1, 1} );
buf.push_back( {2, 2, 2} );
buf.push_back( {3, 3, 3} );
```
The underlying question is: what is the cost of calling `m.getAttrib( handle1 )` many times ?

Comment (hoshiryu) [reply Docs/mesh.md]: Yes you can ;)

File: src/Core/Utils/Attribs.hpp [hunk 12]
```diff
@@ -17,8 +16,7 @@ class Attrib;
 /// An Attrib is data linked to Vertices of a mesh.
```
Comment (nmellado) [inline src/Core/Utils/Attribs.hpp]: I'm not sure this line is true anymore.

Comment (hoshiryu) [reply src/Core/Utils/Attribs.hpp]: sure

File: Docs/mesh.md (hunk 11 above)
Comment (nmellado) [reply Docs/mesh.md]: Can you add the complexity of these functions in the AttribManager methods doc ?
Also, it could be nice to refer from TriangleMesh to AttribManager for the methods that are delegated to AttribManager, something like:
```c++
    /// Get attribute by handle (const).
    /// \see AttribManager::getAttrib
    template <typename T>
    inline const Attrib<T>& getAttrib( AttribHandle<T> h ) const {
        return m_vertexAttribs.getAttrib( h );
    }
```

Comment (hoshiryu) [reply Docs/mesh.md]: yes, forgot the getters and copyAttributes
