### PR TITLE
Check if normals exists before accessing them (fix #688)

### LINKED ISSUE #688: Topological Mesh requires normal vectors, but they are optional
A mesh can exists even if the normal vectors are not set.
However, the constructor of `TopologicalMesh` expect (without tasking or requiring it) and read this attribute:
https://github.com/STORM-IRIT/Radium-Engine/blob/a50a3b45a694855e2fbf2a657656a5e98605af34/src/Core/Geometry/TopologicalMesh.inl#L119
This cause a segfault at runtime.

A way to fix this would be to test if the normal buffer is empty, and skip the normal attribute setting in that case.

### PR DESCRIPTION
**Pull request by nmellado**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bugfix

* **What is the current behavior?** (You can also link to an open issue here)
See #688 

* **What is the new behavior (if this is a feature change)?**
Check if the mesh has normal attributes before copying them

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
 --

### CODE REVIEW

**Comment by dlyr** [comment]
After testing :
"bow tie" vertex is handled by open mesh and has `TopologicalMesh::isManifold(vertexHandle)` returning true.
"double pyramid" as the example here generate invalid faces and could be handled with the `NonManifoldFaceCommand`
I have added some tests to demonstrate this.
OpenMesh doc is misleading on this point, I'll maybe report this upstream, if I found time.

File: src/Core/Geometry/TopologicalMesh.cpp [hunk 1]
```diff
@@ -162,11 +166,13 @@ void copyAttribToCore( TriangleMesh& triMesh, const HandleAndValueVector<T>& dat
 
 //! [Default command implementation]
 struct DefaultNonManifoldFaceCommand {
+    /// \brief details string is printed along with the message
+    DefaultNonManifoldFaceCommand( std::string details = {} ) : m_details {details} {}
```
Comment (nmellado) [inline src/Core/Geometry/TopologicalMesh.cpp:170]: I would prefer that we pass a `struct TopologicalMesh::NonManifoldFaceCommandContext` instead of a `std::string`, which will allow us to add more attributes if needed, and without changing the API.

**Review by nmellado — COMMENTED** [review]
Nice, thanks for the additional change.
Just one suggestion to discuss, and I guess we are good to go.

**Comment by dlyr** [comment]
Well. It’s an internal class. There is no api here  

++ david

**Review by nmellado — COMMENTED** [review]
Ok my bad, I misread your code.
All good for me.

**Comment by dlyr** [comment]
I suspect a bug in fromWedge conversion with normal ctor, even if we need to get rid of this normal ctor and replace it by the fromWedge version, I prefer to investigate before accepting the PR.

**Comment by dlyr** [comment]
Done.

**Review by dlyr — APPROVED** [review]

**Review by dlyr — APPROVED** [review]
